export { default as HomePage } from "./HomePage";
export { default as AboutPage } from "./AboutePage";
export { default as NewsPage } from "./NewsPage";
export { default as CryptocurrencyPage } from "./CryptocurrencyPage";
export { default as WhatIsBitcoinPage } from "./WhatIsBitcoinPage";
export { default as AltCoinsPage } from "./AltCoinsPage";
export { default as LoginPage } from "./LoginPage";
export { default as RegisterPage } from "./RegisterPage";
export { default as CryptoNotesPage } from "./CryptoNotesPage";
